spring:
  application:
    name: rainet-oss
  datasource:
    url: jdbc:postgresql://localhost:5432/rainet
    username: rainet
    password: rainet
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  servlet:
    context-path: /api

logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/rainet}
    username: ${SPRING_DATASOURCE_USERNAME:rainet}
    password: ${SPRING_DATASOURCE_PASSWORD:rainet}

server:
  servlet:
    context-path: ${SPRING_SERVLET_CONTEXT_PATH:/api}

logging:
  level:
    root: INFO
